-- ============================================================
-- SCRIPT SETUP DATABASE SUPABASE - Form Pemakaian Mobil ISM (FIXED)
-- Copy dan Paste seluruh script ini ke SQL Editor di Supabase
-- ============================================================

-- 1. TABEL USERS (Approver & Admin)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nama TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'approver1', -- 'admin', 'approver1', 'approver2'
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert Default Users
INSERT INTO public.users (username, password, nama, email, role) VALUES
('admin', 'integra2026', 'Super Admin', 'admin@integrasolution.id', 'admin'),
('approver1', 'approver123', 'Pak Sanny (Approver 1)', 'sanny.anshory@integrasolution.id', 'approver1'),
('approver2', 'approver123', 'Ibu Devry (Approver 2)', 'devry.handayani@integrasolution.id', 'approver2')
ON CONFLICT (username) DO NOTHING;

-- 2. TABEL VEHICLES (Master Data Kendaraan)
CREATE TABLE IF NOT EXISTS public.vehicles (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  jenis TEXT DEFAULT 'Mobil Penumpang',
  merk TEXT DEFAULT 'Toyota Rush 1.5 G AT',
  nopol TEXT DEFAULT 'B 1731 DZW',
  warna TEXT DEFAULT 'Putih',
  tahun TEXT DEFAULT '2025',
  vin TEXT DEFAULT 'MHKE8FB23JSK021508',
  mesin TEXT DEFAULT '2NR4E10190',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert Default Vehicle
INSERT INTO public.vehicles (id, jenis, merk, nopol, warna, tahun, vin, mesin)
VALUES (1, 'Mobil Penumpang', 'Toyota Rush 1.5 G AT', 'B 1731 DZW', 'Putih', '2025', 'MHKE8FB23JSK021508', '2NR4E10190')
ON CONFLICT (id) DO NOTHING;

-- 3. TABEL SUBMISSIONS (Data Peminjaman Mobil)
CREATE TABLE IF NOT EXISTS public.submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  no_form TEXT UNIQUE NOT NULL,
  tanggal_form TEXT,
  nama TEXT NOT NULL,
  perusahaan TEXT,
  jabatan TEXT,
  alamat TEXT,
  ktp TEXT,
  telepon TEXT,
  email TEXT NOT NULL,
  tujuan TEXT,
  tgl_mulai TEXT,
  waktu_mulai TEXT,
  tgl_selesai TEXT,
  waktu_selesai TEXT,
  durasi NUMERIC DEFAULT 0,
  lokasi_jemput TEXT,
  lokasi_kembali TEXT,
  dengan_driver TEXT,
  jenis TEXT,
  merk TEXT,
  nopol TEXT,
  warna TEXT,
  tahun TEXT,
  vin TEXT,
  mesin TEXT,
  km_awal NUMERIC DEFAULT 0,
  level_bensin NUMERIC DEFAULT 50,
  catatan_kondisi TEXT,
  nama_dari TEXT,
  jabatan_dari TEXT,
  tgl_dari TEXT,
  ttd_dari TEXT,
  nama_ke TEXT,
  jabatan_ke TEXT,
  tgl_ke TEXT,
  ttd_ke TEXT,
  stnk BOOLEAN DEFAULT false,
  kunci_cadangan BOOLEAN DEFAULT false,
  dongkrak BOOLEAN DEFAULT false,
  ban_serep BOOLEAN DEFAULT false,
  segitiga BOOLEAN DEFAULT false,
  p3k BOOLEAN DEFAULT false,
  lainnya TEXT,
  foto_sim_url TEXT,
  approval_status TEXT DEFAULT 'pending', -- 'pending', 'approved1', 'approved2', 'rejected'
  token TEXT DEFAULT gen_random_uuid()::text,
  approver1_note TEXT,
  approver1_at TIMESTAMPTZ,
  approver2_note TEXT,
  approver2_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. TABEL RETURNS (Data Pengembalian Mobil)
CREATE TABLE IF NOT EXISTS public.returns (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  no_form_ret TEXT UNIQUE NOT NULL,
  tanggal_form_ret TEXT,
  ref_no_form TEXT,
  ref_nama TEXT,
  ref_perusahaan TEXT,
  ref_nopol TEXT,
  km_awal NUMERIC DEFAULT 0,
  km_akhir NUMERIC DEFAULT 0,
  km_tempuh NUMERIC DEFAULT 0,
  fuel_level_kembali NUMERIC DEFAULT 50,
  kondisi_kembali TEXT,
  tgl_kembali TEXT,
  waktu_kembali TEXT,
  lokasi_kembali TEXT,
  status_keterlambatan TEXT,
  selisih_hari NUMERIC DEFAULT 0,
  catatan_terlambat TEXT,
  nama_dari TEXT,
  jabatan_dari TEXT,
  tgl_dari TEXT,
  nama_ke TEXT,
  jabatan_ke TEXT,
  tgl_ke TEXT,
  stnk BOOLEAN DEFAULT false,
  kunci_cadangan BOOLEAN DEFAULT false,
  dongkrak BOOLEAN DEFAULT false,
  ban_serep BOOLEAN DEFAULT false,
  segitiga BOOLEAN DEFAULT false,
  p3k BOOLEAN DEFAULT false,
  lainnya TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. STORAGE BUCKET FOTO SIM (Public Access)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('sim-photos', 'sim-photos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policy agar public bisa mengunduh dan mengupload foto SIM
CREATE POLICY "Public Read Access SIM Photos" ON storage.objects FOR SELECT USING (bucket_id = 'sim-photos');
CREATE POLICY "Public Insert Access SIM Photos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'sim-photos');
CREATE POLICY "Public Update Access SIM Photos" ON storage.objects FOR UPDATE USING (bucket_id = 'sim-photos');

-- RLS Enable & Grant Access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.returns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Users Access" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Vehicles Access" ON public.vehicles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Submissions Access" ON public.submissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Returns Access" ON public.returns FOR ALL USING (true) WITH CHECK (true);
